import type { Metadata } from "next";
import "../globals.css";
import { redirect } from "next/navigation";
import { getUserSession } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Admin | Cosmo Crystals",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getUserSession();

  if (!session) {
    redirect("/login");
  }

  return <>{children}</>;
}
